name: FE CD

on:
  workflow_run:
    workflows: ["FE CI"]
    types:
      - completed
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Setup SSH Config & Key
        run: |
          mkdir -p ~/.ssh

          echo "host i-*" >> ~/.ssh/config
          echo "  ProxyCommand sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'\"" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Copy Docker Compose file to Server
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.AWS_EC2_INSTANCE_ID }}:/home/${{ secrets.SERVER_USER }}/

      - name: Deploy to EC2 with Docker
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          aws-region: "ap-northeast-2"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.AWS_EC2_INSTANCE_ID }}

          working-directory: "/home/${{ secrets.SERVER_USER }}/"
          command: |
            sudo su - ${{ secrets.SERVER_USER }} -c '
              cd /home/${{ secrets.SERVER_USER }}/
              docker compose pull
              docker compose up -d
              docker image prune -f
            '
